config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: v2
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-rust-eleuth.sh
        container: qc.acc_clammy-olivine-kudu
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-violet-kudu.sh
        container: qc.doc_leaky-lavender-flamingo
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-magenta-spaniel.sh
        container: qc.doc_flimsy-chestnut-tarantula
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-amethyst-quail.sh
        container: qc.doc_woozy-cyan-goose
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-orange-dalmatian.sh
        container: qc.lic_hasty-buff-binturong
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-plum-sheep.sh
        container: qc.sec_lovely-olivine-rhinoceros
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.beady-bronze-rattlesnake.sh
        container: qc.sty_crabby-flax-cockroach
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-seashell-gorilla.sh
        container: qc.sty_woozy-cream-mongrel
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-wheat-dollar.sh
        container: qc.ver_wimpy-ruby-dragon
timeout: 5400
