config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-red-whale.sh
        container: qc.acc_nippy-silver-crab
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-mauve-schnauzer.sh
        container: qc.doc_freaky-black-woodpecker
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-pear-stoat.sh
        container: qc.doc_bluesy-rose-bee
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-red-flounder.sh
        container: qc.doc_woozy-cornflower-tiger
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-thistle-flounder.sh
        container: qc.lic_paltry-puce-stingray
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-sapphire-zebu.sh
        container: qc.sec_sickly-cardinal-fossa
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-red-dhole.sh
        container: qc.sty_slaphappy-auburn-squirt
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lemon-eel.sh
        container: qc.sty_wiggy-saffron-labradoodle
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-orchid-bandicoot.sh
        container: qc.ver_queasy-black-giraffe
timeout: 5400
