config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.8.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-olivine-sheepdog.sh
        container: qc.acc_lanky-jade-otter
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-persimmon-dachshund.sh
        container: qc.doc_messy-cerulean-quoll
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-heliotrope-greyhound.sh
        container: qc.doc_tacky-violet-moorhen
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-salmon-oriole.sh
        container: qc.doc_messy-grey-stingray
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olivine-sheepdog.sh
        container: qc.lic_muggy-xanthic-catfish
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-grey-mule.sh
        container: qc.sec_leaky-lemon-cuscus
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-linen-millipede.sh
        container: qc.sty_wheezy-sepia-cuscus
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-peach-neanderthal.sh
        container: qc.sty_wimpy-magnolia-catfish
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ultramarine-crocodile.sh
        container: qc.uni_thirsty-corn-caterpillar
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-burgundy-tarsier.sh
        container: qc.ver_chummy-crimson-budgerigar
timeout: 5400
