config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-goldenrod-ladybird.sh
        container: qc.acc_grumpy-periwinkle-foxhound
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-periwinkle-mayfly.sh
        container: qc.doc_beady-seashell-butterfly
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-scarlet-lionfish.sh
        container: qc.doc_lumpy-bronze-rhinoceros
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-viridian-squirrel.sh
        container: qc.doc_beady-taupe-bandicoot
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-vermilion-bird.sh
        container: qc.lic_sickly-gold-dragon
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mustard-chin.sh
        container: qc.sec_homey-aquamarine-paradise
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-lilac-caterpillar.sh
        container: qc.sty_skanky-cream-chicken
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-fuchsia-panda.sh
        container: qc.sty_wheezy-turquoise-spider
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-firebrick-fox.sh
        container: qc.ver_snippy-crimson-maltese
timeout: 5400
