config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-saffron-alligator.sh
        container: qc.acc_trippy-mauve-macaque
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-myrtle-seahorse.sh
        container: qc.doc_beady-teal-chipmunk
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-ultramarine-bear.sh
        container: qc.doc_grumpy-linen-bloodhound
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-seashell-pinscher.sh
        container: qc.doc_woolly-pumpkin-meerkat
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-pink-dolphin.sh
        container: qc.lic_whiny-cornflower-urchin
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-cinnabar-hamster.sh
        container: qc.sec_greasy-charcoal-sparrow
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amaranth-camel.sh
        container: qc.sty_silly-gold-fox
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-teal-gharial.sh
        container: qc.sty_pretty-salmon-jellyfish
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-zucchini-magpie.sh
        container: qc.uni_chummy-taupe-birman
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-beige-wallaby.sh
        container: qc.ver_surly-saffron-rottweiler
timeout: 5400
