config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-violet-axolotl.sh
        container: qc.acc_ugly-brown-bat
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cardinal-meerkat.sh
        container: qc.doc_foggy-khaki-wolverine
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-gold-akita.sh
        container: qc.doc_freaky-rose-setter
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-tangerine-squid.sh
        container: qc.doc_craggy-ecru-axolotl
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-lavender-paradise.sh
        container: qc.lic_pasty-auburn-oriole
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-corn-alligator.sh
        container: qc.sec_tacky-chartreuse-cow
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-carmine-worm.sh
        container: qc.sty_shabby-green-spider
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerise-bee.sh
        container: qc.sty_gamy-razzmatazz-emu
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-olive-beetle.sh
        container: qc.ver_snoopy-razzmatazz-bison
timeout: 5400
