config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-auburn-flamingo.sh
        container: qc.acc_woolly-chocolate-fowl
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-wisteria-rhinoceros.sh
        container: qc.doc_skinny-yellow-capuchin
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-sepia-jackal.sh
        container: qc.doc_boozy-rose-mouse
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-salmon-vulture.sh
        container: qc.doc_jumpy-green-bordeaux
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-orchid-fly.sh
        container: qc.lic_clammy-aquamarine-coyote
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-lilac-goose.sh
        container: qc.sec_wimpy-sepia-woodlouse
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-crimson-eagle.sh
        container: qc.sty_homey-cerulean-zonkey
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cream-jellyfish.sh
        container: qc.sty_silly-chestnut-echidna
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-asparagus-mayfly.sh
        container: qc.uni_woolly-gold-tang
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-orange-mongrel.sh
        container: qc.ver_lanky-ochre-bombay
timeout: 5400
