config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/reshape_inputs
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-dandelion-harrier.sh
        container: qc.acc_droopy-thistle-barracuda
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-olivine-numbat.sh
        container: qc.doc_hilly-smalt-bonobo
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-sangria-argentino.sh
        container: qc.doc_goopy-tangerine-dingo
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-emerald-pinscher.sh
        container: qc.doc_dorky-carmine-magpie
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-brass-oyster.sh
        container: qc.lic_squirrely-lemon-hound
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-chocolate-dalmatian.sh
        container: qc.sec_woolly-celadon-capuchin
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-cobalt-dogfish.sh
        container: qc.sty_flimsy-violet-sparrow
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ruby-gorilla.sh
        container: qc.sty_hasty-rose-chihuahua
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-ochre-husky.sh
        container: qc.ver_geeky-brass-balinese
timeout: 5400
