config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-pumpkin-numbat.sh
        container: qc.acc_sunny-apricot-macaque
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-corn-dachsbracke.sh
        container: qc.doc_boozy-aquamarine-armadillo
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-lilac-seahorse.sh
        container: qc.doc_snappy-black-flamingo
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-flax-kiwi.sh
        container: qc.doc_pretty-amethyst-fish
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-taupe-mayfly.sh
        container: qc.lic_tasty-white-dalmatian
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-denim-cuttlefish.sh
        container: qc.sec_slimy-xanthic-coati
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-pink-buffalo.sh
        container: qc.sty_freaky-scarlet-mule
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-cerise-peccary.sh
        container: qc.sty_hazy-flax-bird
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-puce-lobster.sh
        container: qc.ver_stuffy-cobalt-yak
timeout: 5400
