config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-amethyst-echidna.sh
        container: qc.acc_pasty-magenta-eleuth
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-russet-cattle.sh
        container: qc.doc_freaky-ultramarine-iguana
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-tan-cougar.sh
        container: qc.doc_snazzy-tan-balinese
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-magenta-chinchilla.sh
        container: qc.doc_pasty-periwinkle-quail
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.messy-gamboge-giraffe.sh
        container: qc.lic_slaphappy-chartreuse-bear
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-lavender-ladybird.sh
        container: qc.sec_nippy-fuchsia-cat
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-eggplant-fox.sh
        container: qc.sty_ugly-harlequin-fox
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-khaki-monkey.sh
        container: qc.sty_snazzy-plum-markhor
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-scarlet-stoat.sh
        container: qc.uni_snippy-brown-cow
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-silver-mouse.sh
        container: qc.ver_beady-heliotrope-goose
timeout: 5400
