config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/name_steps
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-ivory-toad.sh
        container: qc.acc_wheezy-chartreuse-sheep
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-denim-oriole.sh
        container: qc.doc_zippy-xanthic-rhinoceros
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-thistle-wombat.sh
        container: qc.doc_skimpy-linen-fossa
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-champagne-beetle.sh
        container: qc.doc_shaggy-xanthic-bulldog
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-peach-avocet.sh
        container: qc.lic_stinky-azure-fowl
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-amethyst-collie.sh
        container: qc.sec_greasy-persimmon-lobster
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-tangerine-raccoon.sh
        container: qc.sty_sickly-ivory-oyster
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-fuchsia-discus.sh
        container: qc.sty_woolly-amethyst-tarantula
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-ecru-labradoodle.sh
        container: qc.uni_pretty-ruby-bobcat
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-pink-mau.sh
        container: qc.ver_muzzy-malachite-buzzard
timeout: 5400
