config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: 2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-brass-scorpion.sh
        container: qc.acc_thirsty-rose-woodpecker
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homely-heliotrope-tarsier.sh
        container: qc.doc_sunny-cyan-stoat
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-buff-iguana.sh
        container: qc.doc_chummy-rust-rottweiler
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-purple-zorse.sh
        container: qc.doc_snazzy-khaki-birman
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-aquamarine-fossa.sh
        container: qc.lic_slimy-tomato-monkey
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-thistle-lemur.sh
        container: qc.sec_flimsy-lavender-ostrich
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-heliotrope-discus.sh
        container: qc.sty_nerdy-green-sheepdog
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-buff-affenpinscher.sh
        container: qc.sty_flaky-mustard-dachsbracke
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-red-termite.sh
        container: qc.ver_chewy-blue-anteater
timeout: 5400
