config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-saffron-angelfish.sh
        container: qc.acc_frumpy-asparagus-bombay
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-heliotrope-chamois.sh
        container: qc.doc_pokey-myrtle-fish
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-scarlet-hyrax.sh
        container: qc.doc_pasty-jade-bird
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-russet-dalmatian.sh
        container: qc.doc_randy-olive-crocodile
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-malachite-malamute.sh
        container: qc.lic_shabby-fuchsia-chameleon
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-sepia-hummingbird.sh
        container: qc.sec_flaky-emerald-labradoodle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lilac-lizard.sh
        container: qc.sty_scaly-azure-stingray
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-vermilion-hedgehog.sh
        container: qc.sty_wimpy-dandelion-blue
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-brass-drever.sh
        container: qc.ver_randy-gold-lynx
timeout: 5400
