config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: release/2.2.0
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-cerise-capybara.sh
        container: qc.acc_shaggy-scarlet-discus
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-silver-fossa.sh
        container: qc.doc_seedy-cardinal-crocodile
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-aqua-paradise.sh
        container: qc.doc_woolly-cinnamon-chin
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-orange-bracke.sh
        container: qc.doc_surly-lavender-terrier
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-eggplant-hornet.sh
        container: qc.lic_leaky-ochre-mule
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-gamboge-gopher.sh
        container: qc.sec_snazzy-azure-macaque
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-chartreuse-tuatara.sh
        container: qc.sty_wiggy-taupe-buzzard
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-chocolate-lionfish.sh
        container: qc.sty_flimsy-grey-seal
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sapphire-chimpanzee.sh
        container: qc.uni_chewy-cerulean-dingo
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-scarlet-snail.sh
        container: qc.ver_wheezy-turquoise-gerbil
timeout: 5400
