config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/reshape_inputs
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-violet-vole.sh
        container: qc.acc_skinny-brown-orangutan
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-pumpkin-meerkat.sh
        container: qc.doc_gimpy-denim-pinscher
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-olivine-tzu.sh
        container: qc.doc_crappy-corn-giraffe
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-heliotrope-gharial.sh
        container: qc.doc_boozy-bronze-harrier
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-amaranth-monster.sh
        container: qc.lic_thirsty-bistre-seal
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-cobalt-yak.sh
        container: qc.sec_pretty-bronze-mongoose
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-tangerine-chinook.sh
        container: qc.sty_droopy-alizarin-zonkey
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-asparagus-starfish.sh
        container: qc.sty_foggy-champagne-anteater
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-auburn-maltese.sh
        container: qc.ver_droopy-auburn-antelope
timeout: 5400
