config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: release/2.0.0
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-cerise-booby.sh
        container: qc.acc_homely-pear-ocelot
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-brass-zorse.sh
        container: qc.doc_crabby-ruby-collie
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-myrtle-cougar.sh
        container: qc.doc_randy-malachite-mongoose
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-burgundy-binturong.sh
        container: qc.doc_snippy-magenta-jellyfish
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-persimmon-ray.sh
        container: qc.lic_cozy-goldenrod-husky
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-salmon-crab.sh
        container: qc.sec_sleazy-pear-iguana
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-amethyst-tamarin.sh
        container: qc.sty_skimpy-brass-akita
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-platinum-hyena.sh
        container: qc.sty_leaky-olivine-molly
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-bronze-guppy.sh
        container: qc.ver_gummy-apricot-quail
timeout: 5400
