config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: release/2.4.1
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-orange-bloodhound.sh
        container: qc.acc_messy-azure-budgerigar
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olive-devil.sh
        container: qc.doc_foggy-periwinkle-hummingbird
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-buff-wildebeest.sh
        container: qc.doc_pasty-aquamarine-hornet
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-emerald-stingray.sh
        container: qc.doc_dorky-pink-javanese
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-mauve-kangaroo.sh
        container: qc.lic_flimsy-magenta-corgi
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-mauve-indri.sh
        container: qc.sec_shaggy-flax-woodlouse
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-gamboge-eleuth.sh
        container: qc.sty_woolly-rust-quail
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-buff-dhole.sh
        container: qc.sty_breezy-taupe-wallaby
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-red-gibbon.sh
        container: qc.uni_clammy-magnolia-crab
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-wheat-cow.sh
        container: qc.ver_skinny-malachite-starfish
timeout: 5400
