config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: test/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gamboge-opossum.sh
        container: qc.acc_paltry-turquoise-bandicoot
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-indigo-opossum.sh
        container: qc.doc_hilly-cornflower-bullfrog
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cream-fish.sh
        container: qc.doc_frumpy-myrtle-deer
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-smalt-foxhound.sh
        container: qc.doc_snippy-mustard-robin
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-brown-coyote.sh
        container: qc.lic_wheezy-flax-coyote
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-orange-dugong.sh
        container: qc.sec_stuffy-bistre-kiwi
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-salmon-sheep.sh
        container: qc.sty_snippy-vermilion-walrus
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-eggplant-emu.sh
        container: qc.sty_wheezy-ecru-cheetah
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-rust-tang.sh
        container: qc.ver_sleepy-chartreuse-beaver
timeout: 5400
