config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-olivine-dachsbracke.sh
        container: qc.acc_paltry-cerulean-echidna
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-amethyst-ladybird.sh
        container: qc.doc_gimpy-chartreuse-chamois
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-thistle-dunker.sh
        container: qc.doc_sloppy-yellow-bison
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-firebrick-peccary.sh
        container: qc.doc_foggy-khaki-sponge
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-heliotrope-barnacle.sh
        container: qc.lic_stinky-chartreuse-dugong
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-wheat-havanese.sh
        container: qc.sec_craggy-ruby-eleuth
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-carmine-iguana.sh
        container: qc.sty_cloudy-azure-bulldog
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-purple-dormouse.sh
        container: qc.sty_goopy-auburn-akita
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-red-magpie.sh
        container: qc.ver_greasy-chartreuse-warthog
timeout: 5400
