config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: 2.4.0
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-saffron-hornet.sh
        container: qc.acc_squeaky-myrtle-akita
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-flax-lion.sh
        container: qc.doc_stuffy-auburn-harrier
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-platinum-molly.sh
        container: qc.doc_boozy-gold-axolotl
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-peach-robin.sh
        container: qc.doc_beady-auburn-horse
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-crimson-butterfly.sh
        container: qc.lic_cheeky-ecru-russel
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ready-smalt-rabbit.sh
        container: qc.sec_lanky-maroon-cat
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-salmon-boar.sh
        container: qc.sty_wiggy-orchid-toucan
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-green-civet.sh
        container: qc.sty_snoopy-buff-eagle
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-asparagus-retriever.sh
        container: qc.uni_lovely-grey-stingray
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-sangria-scorpion.sh
        container: qc.ver_lousy-persimmon-greyhound
timeout: 5400
