config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/name_steps
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-red-rhinoceros.sh
        container: qc.acc_smelly-champagne-bongo
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-orange-mandrill.sh
        container: qc.doc_sleazy-lavender-budgerigar
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-gamboge-mandrill.sh
        container: qc.doc_chummy-coral-coati
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-khaki-wolfhound.sh
        container: qc.doc_nerdy-violet-kudu
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-tangerine-deer.sh
        container: qc.lic_gamy-gold-hare
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-emerald-meerkat.sh
        container: qc.sec_nerdy-maroon-beetle
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-auburn-orangutan.sh
        container: qc.sty_tacky-cream-raccoon
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-sangria-coyote.sh
        container: qc.sty_freaky-khaki-chow
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-bistre-newt.sh
        container: qc.uni_smelly-amber-buzzard
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-mauve-russel.sh
        container: qc.ver_whiny-xanthic-neanderthal
timeout: 5400
