config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-turquoise-bulldog.sh
        container: qc.acc_lumpy-alizarin-uakari
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-jade-whale.sh
        container: qc.doc_gloppy-cardinal-ibis
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-flax-moorhen.sh
        container: qc.doc_squirrely-myrtle-stingray
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-turquoise-tiger.sh
        container: qc.doc_geeky-chocolate-walrus
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-dog.sh
        container: qc.lic_nerdy-mustard-robin
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-brass-swan.sh
        container: qc.sec_lousy-bronze-javanese
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-yellow-dingo.sh
        container: qc.sty_gamy-wisteria-sheep
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-yellow-cichlid.sh
        container: qc.sty_woozy-aquamarine-spaniel
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-firebrick-squirt.sh
        container: qc.uni_scummy-tomato-sheepdog
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-apricot-dane.sh
        container: qc.ver_chummy-azure-catfish
timeout: 5400
