config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-scarlet-chin.sh
        container: qc.acc_cozy-black-goose
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-vermilion-bordeaux.sh
        container: qc.doc_hasty-asparagus-chihuahua
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-brass-javanese.sh
        container: qc.doc_skanky-alizarin-boar
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-azure-albatross.sh
        container: qc.doc_surly-mustard-barnacle
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-wheat-paradise.sh
        container: qc.lic_crappy-peach-chihuahua
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-rust-spaniel.sh
        container: qc.sec_cozy-chocolate-capybara
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-grey-deer.sh
        container: qc.sty_muzzy-red-robin
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-sapphire-alligator.sh
        container: qc.sty_scanty-mauve-hippopotamus
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-harlequin-kiwi.sh
        container: qc.uni_hazy-orange-chipmunk
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-charcoal-caiman.sh
        container: qc.ver_freaky-plum-lionfish
timeout: 5400
