config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-chartreuse-baboon.sh
        container: qc.acc_geeky-aquamarine-capybara
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-eggplant-birman.sh
        container: qc.doc_snappy-chartreuse-flounder
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-mustard-mongrel.sh
        container: qc.doc_breezy-cyan-wolverine
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-silver-gopher.sh
        container: qc.doc_blurry-peach-bombay
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-pumpkin-wolfhound.sh
        container: qc.lic_goopy-seashell-zonkey
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-black-sponge.sh
        container: qc.sec_silly-zucchini-moorhen
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-buff-termite.sh
        container: qc.sty_pokey-amber-barb
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-apricot-reindeer.sh
        container: qc.sty_scaly-malachite-wasp
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-seashell-spaniel.sh
        container: qc.uni_sleepy-vermilion-dog
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-razzmatazz-hyrax.sh
        container: qc.ver_crappy-ultramarine-monster
timeout: 5400
