config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/reshape_inputs
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.homey-xanthic-warthog.sh
        container: qc.acc_silly-cornflower-abyssinian
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.silly-harlequin-crane.sh
        container: qc.doc_baggy-dandelion-vole
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-khaki-dalmatian.sh
        container: qc.doc_shaky-lime-orangutan
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-pear-tarantula.sh
        container: qc.doc_gimpy-jade-caiman
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-pear-armadillo.sh
        container: qc.lic_jumpy-salmon-mouse
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-platinum-turkey.sh
        container: qc.sec_hasty-sangria-tarantula
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-ivory-pinscher.sh
        container: qc.sty_queasy-russet-squirrel
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-orange-bandicoot.sh
        container: qc.sty_tasty-ultramarine-cassowary
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-corn-discus.sh
        container: qc.ver_chummy-magenta-civet
timeout: 5400
