config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: test/im
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ochre-blue.sh
        container: qc.acc_pretty-lemon-lemming
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-wheat-manatee.sh
        container: qc.doc_stuffy-platinum-snake
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-plum-mandrill.sh
        container: qc.doc_whiny-chartreuse-zonkey
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-vermilion-rottweiler.sh
        container: qc.doc_crabby-ruby-dalmatian
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-grey-termite.sh
        container: qc.lic_gimpy-tangerine-angelfish
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-jade-dalmatian.sh
        container: qc.sec_seedy-zucchini-tarsier
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-xanthic-maltese.sh
        container: qc.sty_wheezy-beige-chicken
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-mustard-vole.sh
        container: qc.sty_boozy-wisteria-avocet
  QC.Uni:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action tox:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lavender-tzu.sh
        container: qc.uni_lovely-alizarin-goose
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-platinum-camel.sh
        container: qc.ver_skinny-myrtle-grasshopper
timeout: 5400
