config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-assessment-action:
      branch: feature/criteria_workflows
      repo: https://github.com/EOSC-synergy/sqaaas-assessment-action
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.13
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-yellow-frog.sh
        container: qc.acc_stinky-lavender-liger
  QC.Doc:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-tomato-wasp.sh
        container: qc.doc_muzzy-copper-quokka
      github.com/EOSC-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-indigo-fousek.sh
        container: qc.doc_crabby-chartreuse-hippopotamus
      github.com/EOSC-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-silver-hyrax.sh
        container: qc.doc_hasty-platinum-hyena
  QC.Lic:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-crimson-setter.sh
        container: qc.lic_hazy-carmine-bracke
  QC.Sec:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cornflower-setter.sh
        container: qc.sec_trippy-dandelion-chamois
  QC.Sty:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-woodlouse.sh
        container: qc.sty_skinny-zucchini-mole
      github.com/EOSC-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-russet-tortoise.sh
        container: qc.sty_craggy-fuchsia-tuatara
  QC.Ver:
    repos:
      github.com/EOSC-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-taupe-whippet.sh
        container: qc.ver_shaggy-xanthic-snake
timeout: 5400
