config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/eosc-synergy/sqaaas-assessment-action:
      branch: main
      repo: https://github.com/eosc-synergy/sqaaas-assessment-action
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-teal-tiger.sh
        container: qc.acc_slimy-corn-deer
  QC.Doc:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-eggplant-mist.sh
        container: qc.doc_chewy-platinum-cockroach
      github.com/eosc-synergy/sqaaas-assessment-action git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cinnamon-turtle.sh
        container: qc.doc_whiny-blue-squid
      github.com/eosc-synergy/sqaaas-assessment-action markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-periwinkle-lobster.sh
        container: qc.doc_nippy-cobalt-beagle
  QC.Lic:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action licensee:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-charcoal-bongo.sh
        container: qc.lic_woozy-buff-falcon
  QC.Sec:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-chocolate-hare.sh
        container: qc.sec_leaky-turquoise-neanderthal
  QC.Sty:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action flake8:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-silver-yak.sh
        container: qc.sty_paltry-carmine-whippet
      github.com/eosc-synergy/sqaaas-assessment-action hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-pear-guppy.sh
        container: qc.sty_baggy-beige-otter
  QC.Uni:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action pytest:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-red-chamois.sh
        container: qc.uni_bumpy-buff-scorpion
  QC.Ver:
    repos:
      github.com/eosc-synergy/sqaaas-assessment-action get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-emerald-gar.sh
        container: qc.ver_boozy-harlequin-penguin
timeout: 5400
